import { headers } from 'next/headers';
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/context/ThemeContext'
import 'react-toastify/dist/ReactToastify.css';
import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space' });

export const metadata: Metadata = {
  title: "Bedir Gocmez",
  description: "Generated by Bedir Gocmez with Next.js",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const theme = headersList.get('x-theme') === 'light' ? 'light' : 'dark';

  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable} ${theme}`}>
      <body className='pt-[70px]'>
        <ThemeProvider>
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
