import { cookies } from 'next/headers';
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/context/ThemeContext'
import 'react-toastify/dist/ReactToastify.css';
import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space' });

export const metadata: Metadata = {
  title: "Bedir Gocmez",
  description: "Generated by Bedir Gocmez with Next.js",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = (await cookieStore).get('theme-bdr-portfolio')?.value as 'light' | 'dark' || 'dark';

  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme-bdr-portfolio');
                  var mode = theme === 'light' ? 'light' : 'dark';
                  document.documentElement.classList.add(mode);
                  document.documentElement.setAttribute('data-theme', mode);
                } catch(e) {}
              })();
            `,
          }}
        ></script>
      </head>
      <body className='pt-[70px]'>
        <ThemeProvider serverTheme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
